---
# Aucun handler requis ---
- name: Vérifier curl
  ansible.builtin.command:
    cmd: curl --version
  register: curl_version
  changed_when: false

- name: Vérifier git
  ansible.builtin.command:
    cmd: git --version
  register: git_version
  changed_when: false

- name: Vérifier Docker
  ansible.builtin.command:
    cmd: docker --version
  register: docker_version
  changed_when: false

- name: Vérifier kubectl
  ansible.builtin.command:
    cmd: kubectl version --client
  register: kubectl_version
  changed_when: false

- name: Vérifier Helm
  ansible.builtin.command:
    cmd: helm version --short
  register: helm_version
  changed_when: false

- name: Vérifier Minikube
  ansible.builtin.command:
    cmd: minikube version
  register: minikube_version
  changed_when: false

- name: Afficher le résumé des outils installés
  ansible.builtin.debug:
    msg:
      - "{{ curl_version.stdout_lines[0] }}"
      - "{{ git_version.stdout }}"
      - "{{ docker_version.stdout }}"
      - "{{ kubectl_version.stdout_lines[0] }}"
      - "{{ helm_version.stdout }}"
      - "{{ minikube_version.stdout_lines[0] }}"