---
project_name: kubernetes_template

system_packages:
  - curl
  - wget
  - git
  - unzip
  - ca-certificates
  - gnupg
  - lsb-release
  - apt-transport-https
  - software-properties-common

docker_install: true
docker_manage_service: false
docker_service_enabled: true
docker_service_state: started
docker_users:
  - "{{ ansible_user_id }}"

kubectl_install: true
kubectl_minor_version: "v1.33"

helm_install: true

minikube_install: true
minikube_version: "v1.36.0"
minikube_driver: docker
minikube_profile: minikube
minikube_start_cluster: false