---
- name: Installer dépendances Helm
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: true
  when:
    - ansible_os_family == "Debian"
    - helm_install | bool

- name: Créer dossier keyrings Helm
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  when:
    - helm_install | bool

- name: Télécharger clé GPG Helm
  ansible.builtin.shell: |
    curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor -o /usr/share/keyrings/helm.gpg
  args:
    creates: /usr/share/keyrings/helm.gpg
  when:
    - ansible_os_family == "Debian"
    - helm_install | bool

- name: Ajouter le dépôt Helm
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
    filename: helm-stable-debian
    state: present
  when:
    - ansible_os_family == "Debian"
    - helm_install | bool

- name: Installer Helm
  ansible.builtin.apt:
    name: helm
    state: present
    update_cache: true
  when:
    - ansible_os_family == "Debian"
    - helm_install | bool

- name: Vérifier installation Helm
  ansible.builtin.command:
    cmd: helm version --short
  register: helm_check
  changed_when: false

- name: Afficher version Helm
  ansible.builtin.debug:
    var: helm_check.stdout