---
- name: Installer les dépendances kubectl
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: true
  when:
    - ansible_os_family == "Debian"
    - kubectl_install | bool

- name: Créer le dossier keyrings APT
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  when:
    - ansible_os_family == "Debian"
    - kubectl_install | bool

- name: Télécharger clé Kubernetes
  ansible.builtin.shell: |
    curl -fsSL "https://pkgs.k8s.io/core:/stable:/{{ kubectl_minor_version }}/deb/Release.key" | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when:
    - ansible_os_family == "Debian"
    - kubectl_install | bool

- name: Ajouter le dépôt Kubernetes
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubectl_minor_version }}/deb/ /"
    filename: kubernetes
    state: present
  when:
    - ansible_os_family == "Debian"
    - kubectl_install | bool

- name: Installer kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present
    update_cache: true
  when:
    - ansible_os_family == "Debian"
    - kubectl_install | bool