deployment:
  kong:
    enabled: true

proxy:
  enabled: true

  type: NodePort

admin:
  enabled: true

ingressController:
  enabled: true

env:

  database: "off"

resources:

  requests:
    cpu: 200m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi